'use client';

import { usePathname } from 'next/navigation';

export default function Footer() {
  const pathname = usePathname();
  const isTopicPage = pathname.startsWith('/topic/');

  return (
    <footer style={{
      textAlign: 'center',
      padding: '32px 48px',
      borderTop: '1px solid var(--border)',
    }}>
      <p style={{ fontSize: 13, color: 'var(--ink-muted)' }}>
        {isTopicPage
          ? 'Analysis generated by ClearSignal'
          : '\u00A9 2026 ClearSignal \u2014 Tracking media coverage across the political spectrum.'}
      </p>
    </footer>
  );
}
